
# Add sbin directories to PATH.  This is useful on systems that have sudo
echo $PATH | grep -Eq "(^|:)/sbin(:|)"     || export PATH=$PATH:/sbin
echo $PATH | grep -Eq "(^|:)/usr/sbin(:|)" || export PATH=$PATH:/usr/sbin

# Add user dirctories to the path
if [[ ! "$PATH" == *"$HOME"/.local/bin* ]]; then
	export PATH=~/.local/bin:$PATH
fi

# Add user dirctories to the path
if [[ ! "$PATH" == *"$HOME"/installs/setup/scripts* ]]; then
    export PATH=$PATH:${HOME}/installs/setup/scripts
fi

# Add user dirctories to the path
# if [[ ! "$PATH" == *"$HOME"/tools/llvm/bin* ]]; then
#     export PATH=$PATH:${HOME}/tools/llvm/bin
# fi

# this part is sourced by /etc/profile, but somehow looses it's effect during startx
# so need to source it again
if [ -x /etc/profile.d/bash_completion.sh ];  then
   . /etc/profile.d/bash_completion.sh
fi

# Taskwarrior
if [ -f "$HOME"/.bash_completion.d/task.sh ];  then
   . "$HOME"/.bash_completion.d/task.sh
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
#. "$HOME/.cargo/env"

if [ -f "$HOME"/.bash_config.sh ]; then
    . "$HOME"/.bash_config.sh
else
    echo "$HOME"/bash_config.sh is missing. Did you create the links?
fi

# Set Capslock as additional Ctrl key
# It's better to use CapsLock as Language Input switch
# setxkbmap -option "ctrl:nocaps"

# Set right alt as Compose key, the keys mappings are defined in ~/.XCompose
# Now the umlaute can be inserted like this: ralt + a = ä
[ -f ~/.XCompose ] && setxkbmap -option compose:ralt

#[ -f ~/.conda.bash ] && source ~/.conda.bash
