
set hidden
set nohlsearch
set ignorecase smartcase
set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab
set smarttab
set autoindent smartindent
set path=.,,**
set complete-=i
set pumheight=15
set updatetime=400
set wildmenu wildignorecase
set wildignore+=*.o,*.so,*/.git/*,*/build/*,*/.cache/*
set wildmode=list:longest,list:full
set tags=./tags;,tags;./.tags;,.tags;
set noswapfile nobackup noundofile
set mouse=a ttymouse=xterm2
set completeopt-=preview
set clipboard=unnamedplus	"use system clipboard

set laststatus=2
set statusline=%f%m%=
set statusline+=\ %y\ Col:%2c\ %3l\/%L\ %2P

set linebreak
set showbreak=>>

" set fillchars=vert:┃
set diffopt+=vertical

highlight Pmenu ctermbg=gray guibg=gray
highlight PmenuSel cterm=bold ctermbg=lightgray gui=bold guibg=lightgray

if (has("termguicolors"))
  " https://github.com/vim/vim/issues/993#issuecomment-255651605
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

  set termguicolors
endif

set grepprg=LC_ALL=C\ grep\ -nrsH
if executable('ag')
  set grepprg=ag
endif

" open quick window / location list when there some results
" https://noahfrederick.com/log/vim-streamlining-grep
augroup init_quickfix
  autocmd!
  autocmd QuickFixCmdPost [^l]* cwindow
  autocmd QuickFixCmdPost l* lwindow
  autocmd WinEnter * if winnr('$') == 1 && &buftype == "quickfix"|q|endif
augroup END

" press enter to choose the selection from completion menu
"inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

let mapleader=" "

nnoremap 0 	^
nnoremap Y 	y$

imap jk <Esc>
imap kj <Esc>

"navigate around window splits with single key combo
nmap <silent> <C-k> :wincmd k<CR>
nmap <silent> <C-j> :wincmd j<CR>
nmap <silent> <C-h> :wincmd h<CR>
nmap <silent> <C-l> :wincmd l<CR>

"find files
"if don't want to alter the path, try: `:find **/*` instead
nnoremap <leader>f  :find *
nnoremap <leader>F  :sfind *

"find buffer
nnoremap <leader>b :ls<CR>:b<Space>

"searching in files
nnoremap <leader>s	:vimgrep //j **<left><left><left><left><left>
nnoremap <leader>S	:silent grep!<space>


" ---------------------------------------------------------
" plugins config (pre)
" ---------------------------------------------------------
runtime user/start.vim
runtime user/ale.vim

" load plugins
"---------------------------------------------------------------
call plug#begin("~/.vim/plugged")
Plug 'junegunn/vim-plug'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-unimpaired'

" Plug 'ackyshake/VimCompletesMe'
Plug 'lifepillar/vim-mucomplete'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'sirver/UltiSnips'
Plug 'honza/vim-snippets'
Plug 'dense-analysis/ale'
"Plug 'derekwyatt/vim-fswitch'
"Plug 'ludovicchabant/vim-gutentags'
"Plug 'preservim/tagbar'
"Plug 'ivalkeen/vim-ctrlp-tjump'
Plug 'xavierd/clang_complete'

Plug 'lambdalisue/fern.vim'
Plug 'lambdalisue/fern-hijack.vim'
Plug 'lambdalisue/fern-git-status.vim'
Plug 'airblade/vim-gitgutter'

Plug 'romainl/Apprentice'
Plug 'lifepillar/vim-gruvbox8'
call plug#end()

set background=dark
colorscheme apprentice

if has("gui_running")
	set background=light
	let g:gruvbox_italics = 0
	colorscheme gruvbox8_hard
	set guifont=DejaVu\ Sans\ Mono\ 12
	set lines=40 columns=120
	set guioptions -=m "disable menu
	set guioptions -=T "disable toolbar
	set guioptions -=r "disable right scroll
	set mouse=a
	"set guicursor+=a:blinkon0
endif

" plugins config (post)
"---------------------------------------------------------------
runtime user/plugins.vim
runtime user/fern.vim

filetype plugin indent on
syntax on
